stages:
  - build
  - test

variables:
  DOCKER_TLS_CERTDIR: ""
  GIT_STRATEGY: clone
  REGISTRY_USER: sylvain-lissy
  APPLICATION: demo-python-flask
  LATEST_IMAGE: $REGISTRY_USER/$APPLICATION:latest
  RELEASE_IMAGE: $REGISTRY_USER/$APPLICATION:$CI_BUILD_REF_NAME
  DOCKER_DRIVER: overlay

before_script:
  - echo "Starting"
  - export DOCKER_IMAGE=$RELEASE_IMAGE
  - if [ "$CI_BUILD_REF_NAME" == "master" ]; then export DOCKER_IMAGE=$LATEST_IMAGE; fi
  - echo "Build docker image $DOCKER_IMAGE"

compile:
    stage: build
    image: docker:latest
    services: 
      - docker:dind
    script:
      - echo $CI_REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
      - echo Building $DOCKER_IMAGE
      - docker build -t $DOCKER_IMAGE .
      - echo Deploying $DOCKER_IMAGE
      - docker push $DOCKER_IMAGE

test: 
  stage: test
  image: docker:latest
  services: 
    - docker:dind
  script:
    - docker run $DOCKER_IMAGE
